# Please refer https://docs.docker.com/compose to learn more about Docker Compose.

# This is a sample docker-compose file with two services
# 1. yourwebapp is an sample web service where the docker container image will be built from the Dockerfile as
#    part of starting the compose.
# 2. redis is an existing image hosted in docker hub.
#docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d --name elastic docker.elastic.co/elasticsearch/elasticsearch:7.7.0
#docker run --link elastic:elasticsearch -p 5601:5601 --name kibana -d docker.elastic.co/kibana/kibana:7.7.0
version: '3.4'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      container_name: elastic
      ports:
          - "9200:9200"
          - "9300:9300"
    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.2
      container_name: kibana
      ports:
          - "5601:5601"
      depends_on:
          - elasticsearch